version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=spring_leaflet
      - POSTGRES_USER=spring_leaflet
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
  spring:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
